version: 2.1

executors:
  ios-build-machine:
    macos:
      xcode: '13.4.1'

jobs:
  build:
    docker:
      - image: circleci/node:16.13.0
    working_directory: ~/project
    steps:
      - checkout
      - run: yarn install
      - run: 
        name: Lerna install
        command: |
          yarn add global add lerna@6.0.1
          echo 'export PATH="$PATH:`yarn global bin`"' >> $BASH_ENV
      - run:
        name: lerna bootstrap --no-ci
        command: lerna bootstrap --no-ci
        no_output_timeout: 20m
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            yarn global add fastlane
            fastlane ios deploy
          fi
