export declare const colors: {
  transparent: string;
  white: string;
  black: string;
  green: string;
  blue: string;
  pink: string;
  gold: string;
  darkBlue: string;
  darkestBlue: string;
  gray: string;
  lightGray: string;
  borderGray: string;
  blackOpacity: string;
  whiteOpacity: string;
  yellow: string;
  orange: string;
  blueOpacity: string;
  grayOpacity: string;
  darkOpacity: string;
};
