import React, { ReactNode } from 'react';
import { ViewProps, ViewStyle } from 'react-native';
export interface IPropsDiv {
  margin?: Array<number> | number;
  padding?: Array<number> | number;
  pt?: number;
  pr?: number;
  pb?: number;
  pl?: number;
  mt?: number;
  mr?: number;
  mb?: number;
  ml?: number;
  width?: number | string;
  height?: number | string;
  flex?: number;
  row?: boolean;
  column?: boolean;
  center?: boolean;
  middle?: boolean;
  alignLeft?: boolean;
  alignRight?: boolean;
  left?: boolean;
  right?: boolean;
  top?: boolean;
  bottom?: boolean;
  centerSelf?: boolean;
  startSelf?: boolean;
  endSelf?: boolean;
  baselineSelf?: boolean;
  radius?: number;
  shadow?: boolean;
  backgroundColor?: string;
  space?: 'around' | 'between' | 'evenly';
  animated?: boolean;
  wrap?: 'wrap' | 'nowrap' | 'wrap-reverse';
  white?: boolean;
  black?: boolean;
  green?: boolean;
  blue?: boolean;
  pink?: boolean;
  gold?: boolean;
  darkBlue?: boolean;
  darkestBlue?: boolean;
  gray?: boolean;
  lightGray?: boolean;
  yellow?: boolean;
  orange?: boolean;
  zIndex?: number;
  overflow?: 'visible' | 'hidden' | 'scroll';
  borderWidth?: number;
  borderColor?: string;
  card?: boolean;
  absolute?: boolean;
  relative?: boolean;
  positionTop?: number;
  positionRight?: number;
  positionBottom?: number;
  positionLeft?: number;
  borderStyle?: 'solid' | 'dotted' | 'dashed';
  style?: ViewStyle;
  children?: ReactNode | JSX.Element;
}
export declare const Div: React.FC<ViewProps & IPropsDiv>;
